config:
  credit:
    full     : 3
    interval : 1200
    increment: 1
camera:
  - name    : frontcam
    hostname: frontcam.shortbus.lan
  - name    : backcam
    hostname: backcam.shortbus.lan
  - name    : drivewaycam
    hostname: drivewaycam.shortbus.lan
  - name    : wirelesscam
    hostname: wirelesscam.shortbus.lan
