config:
  credit_full      : 3
  credit_interval  : 1200
  credit_increment : 1
cameras:
  - name     : frontcam
    hostname : frontcam.whisk.ee
    zip      : 40071
    state    : KY
  - name     : backcam
    hostname : backcam.whisk.ee
    zip      : 40071
    state    : KY
  - name     : drivewaycam
    hostname : drivewaycam.whisk.ee
    zip      : 40071
    state    : KY
  - name     : wirelesscam
    hostname : wirelesscam.whisk.ee
    zip      : 40071
    state    : KY
    no_osd   : true
